//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AchEntura
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosAbono", Namespace="http://ach.entura.com.mx/")]
    public partial class DatosAbono : object
    {
        
        private string Clave_referenciaField;
        
        private string Folio_proveedorField;
        
        private System.DateTime Fecha_hora_operacionField;
        
        private string Tipo_monedaField;
        
        private decimal MontoField;
        
        private decimal ComisionField;
        
        private string Nombre_ordenanteField;
        
        private string Tipo_cuenta_ordenanteField;
        
        private string Cuenta_ordenanteField;
        
        private string Nombre_beneficiarioField;
        
        private string Tipo_cuenta_beneficiarioField;
        
        private string Cuenta_beneficiarioField;
        
        private string Banco_origenField;
        
        private string Cooperativa_origenField;
        
        private string Banco_destinoField;
        
        private string Cooperativa_destinoField;
        
        private string Identificador_origenField;
        
        private string Identificador_beneficiarioField;
        
        private string Concepto_pagoField;
        
        private string FirmaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Clave_referencia
        {
            get
            {
                return this.Clave_referenciaField;
            }
            set
            {
                this.Clave_referenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Folio_proveedor
        {
            get
            {
                return this.Folio_proveedorField;
            }
            set
            {
                this.Folio_proveedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha_hora_operacion
        {
            get
            {
                return this.Fecha_hora_operacionField;
            }
            set
            {
                this.Fecha_hora_operacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tipo_moneda
        {
            get
            {
                return this.Tipo_monedaField;
            }
            set
            {
                this.Tipo_monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Comision
        {
            get
            {
                return this.ComisionField;
            }
            set
            {
                this.ComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nombre_ordenante
        {
            get
            {
                return this.Nombre_ordenanteField;
            }
            set
            {
                this.Nombre_ordenanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Tipo_cuenta_ordenante
        {
            get
            {
                return this.Tipo_cuenta_ordenanteField;
            }
            set
            {
                this.Tipo_cuenta_ordenanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Cuenta_ordenante
        {
            get
            {
                return this.Cuenta_ordenanteField;
            }
            set
            {
                this.Cuenta_ordenanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Nombre_beneficiario
        {
            get
            {
                return this.Nombre_beneficiarioField;
            }
            set
            {
                this.Nombre_beneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Tipo_cuenta_beneficiario
        {
            get
            {
                return this.Tipo_cuenta_beneficiarioField;
            }
            set
            {
                this.Tipo_cuenta_beneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Cuenta_beneficiario
        {
            get
            {
                return this.Cuenta_beneficiarioField;
            }
            set
            {
                this.Cuenta_beneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Banco_origen
        {
            get
            {
                return this.Banco_origenField;
            }
            set
            {
                this.Banco_origenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Cooperativa_origen
        {
            get
            {
                return this.Cooperativa_origenField;
            }
            set
            {
                this.Cooperativa_origenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Banco_destino
        {
            get
            {
                return this.Banco_destinoField;
            }
            set
            {
                this.Banco_destinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Cooperativa_destino
        {
            get
            {
                return this.Cooperativa_destinoField;
            }
            set
            {
                this.Cooperativa_destinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Identificador_origen
        {
            get
            {
                return this.Identificador_origenField;
            }
            set
            {
                this.Identificador_origenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Identificador_beneficiario
        {
            get
            {
                return this.Identificador_beneficiarioField;
            }
            set
            {
                this.Identificador_beneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Concepto_pago
        {
            get
            {
                return this.Concepto_pagoField;
            }
            set
            {
                this.Concepto_pagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Firma
        {
            get
            {
                return this.FirmaField;
            }
            set
            {
                this.FirmaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAbono", Namespace="http://ach.entura.com.mx/")]
    public partial class RespuestaAbono : object
    {
        
        private string Codigo_respuestaField;
        
        private string Descripcion_respuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo_respuesta
        {
            get
            {
                return this.Codigo_respuestaField;
            }
            set
            {
                this.Codigo_respuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion_respuesta
        {
            get
            {
                return this.Descripcion_respuestaField;
            }
            set
            {
                this.Descripcion_respuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosActualizacionEnvio", Namespace="http://ach.entura.com.mx/")]
    public partial class DatosActualizacionEnvio : object
    {
        
        private string Clave_referenciaField;
        
        private string Folio_proveedorField;
        
        private string EstadoField;
        
        private string Mensaje_referenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Clave_referencia
        {
            get
            {
                return this.Clave_referenciaField;
            }
            set
            {
                this.Clave_referenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Folio_proveedor
        {
            get
            {
                return this.Folio_proveedorField;
            }
            set
            {
                this.Folio_proveedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mensaje_referencia
        {
            get
            {
                return this.Mensaje_referenciaField;
            }
            set
            {
                this.Mensaje_referenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaActualizacionEnvio", Namespace="http://ach.entura.com.mx/")]
    public partial class RespuestaActualizacionEnvio : object
    {
        
        private string Codigo_respuestaField;
        
        private string Descripcion_respuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo_respuesta
        {
            get
            {
                return this.Codigo_respuestaField;
            }
            set
            {
                this.Codigo_respuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion_respuesta
        {
            get
            {
                return this.Descripcion_respuestaField;
            }
            set
            {
                this.Descripcion_respuestaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ach.entura.com.mx/", ConfigurationName="AchEntura.ACH_ServiceSoap")]
    public interface ACH_ServiceSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento envio del espacio de nombres http://ach.entura.com.mx/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ach.entura.com.mx/Deposito_ACH", ReplyAction="*")]
        AchEntura.Deposito_ACHResponse Deposito_ACH(AchEntura.Deposito_ACHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ach.entura.com.mx/Deposito_ACH", ReplyAction="*")]
        System.Threading.Tasks.Task<AchEntura.Deposito_ACHResponse> Deposito_ACHAsync(AchEntura.Deposito_ACHRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento datos del espacio de nombres http://ach.entura.com.mx/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ach.entura.com.mx/Actualizacion_Envio_ACH", ReplyAction="*")]
        AchEntura.Actualizacion_Envio_ACHResponse Actualizacion_Envio_ACH(AchEntura.Actualizacion_Envio_ACHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ach.entura.com.mx/Actualizacion_Envio_ACH", ReplyAction="*")]
        System.Threading.Tasks.Task<AchEntura.Actualizacion_Envio_ACHResponse> Actualizacion_Envio_ACHAsync(AchEntura.Actualizacion_Envio_ACHRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Deposito_ACHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deposito_ACH", Namespace="http://ach.entura.com.mx/", Order=0)]
        public AchEntura.Deposito_ACHRequestBody Body;
        
        public Deposito_ACHRequest()
        {
        }
        
        public Deposito_ACHRequest(AchEntura.Deposito_ACHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ach.entura.com.mx/")]
    public partial class Deposito_ACHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AchEntura.DatosAbono envio;
        
        public Deposito_ACHRequestBody()
        {
        }
        
        public Deposito_ACHRequestBody(AchEntura.DatosAbono envio)
        {
            this.envio = envio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Deposito_ACHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deposito_ACHResponse", Namespace="http://ach.entura.com.mx/", Order=0)]
        public AchEntura.Deposito_ACHResponseBody Body;
        
        public Deposito_ACHResponse()
        {
        }
        
        public Deposito_ACHResponse(AchEntura.Deposito_ACHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ach.entura.com.mx/")]
    public partial class Deposito_ACHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AchEntura.RespuestaAbono Deposito_ACHResult;
        
        public Deposito_ACHResponseBody()
        {
        }
        
        public Deposito_ACHResponseBody(AchEntura.RespuestaAbono Deposito_ACHResult)
        {
            this.Deposito_ACHResult = Deposito_ACHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizacion_Envio_ACHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizacion_Envio_ACH", Namespace="http://ach.entura.com.mx/", Order=0)]
        public AchEntura.Actualizacion_Envio_ACHRequestBody Body;
        
        public Actualizacion_Envio_ACHRequest()
        {
        }
        
        public Actualizacion_Envio_ACHRequest(AchEntura.Actualizacion_Envio_ACHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ach.entura.com.mx/")]
    public partial class Actualizacion_Envio_ACHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AchEntura.DatosActualizacionEnvio datos;
        
        public Actualizacion_Envio_ACHRequestBody()
        {
        }
        
        public Actualizacion_Envio_ACHRequestBody(AchEntura.DatosActualizacionEnvio datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizacion_Envio_ACHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizacion_Envio_ACHResponse", Namespace="http://ach.entura.com.mx/", Order=0)]
        public AchEntura.Actualizacion_Envio_ACHResponseBody Body;
        
        public Actualizacion_Envio_ACHResponse()
        {
        }
        
        public Actualizacion_Envio_ACHResponse(AchEntura.Actualizacion_Envio_ACHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ach.entura.com.mx/")]
    public partial class Actualizacion_Envio_ACHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AchEntura.RespuestaActualizacionEnvio Actualizacion_Envio_ACHResult;
        
        public Actualizacion_Envio_ACHResponseBody()
        {
        }
        
        public Actualizacion_Envio_ACHResponseBody(AchEntura.RespuestaActualizacionEnvio Actualizacion_Envio_ACHResult)
        {
            this.Actualizacion_Envio_ACHResult = Actualizacion_Envio_ACHResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ACH_ServiceSoapChannel : AchEntura.ACH_ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ACH_ServiceSoapClient : System.ServiceModel.ClientBase<AchEntura.ACH_ServiceSoap>, AchEntura.ACH_ServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ACH_ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ACH_ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ACH_ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ACH_ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ACH_ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ACH_ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ACH_ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ACH_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AchEntura.Deposito_ACHResponse AchEntura.ACH_ServiceSoap.Deposito_ACH(AchEntura.Deposito_ACHRequest request)
        {
            return base.Channel.Deposito_ACH(request);
        }
        
        public AchEntura.RespuestaAbono Deposito_ACH(AchEntura.DatosAbono envio)
        {
            AchEntura.Deposito_ACHRequest inValue = new AchEntura.Deposito_ACHRequest();
            inValue.Body = new AchEntura.Deposito_ACHRequestBody();
            inValue.Body.envio = envio;
            AchEntura.Deposito_ACHResponse retVal = ((AchEntura.ACH_ServiceSoap)(this)).Deposito_ACH(inValue);
            return retVal.Body.Deposito_ACHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AchEntura.Deposito_ACHResponse> AchEntura.ACH_ServiceSoap.Deposito_ACHAsync(AchEntura.Deposito_ACHRequest request)
        {
            return base.Channel.Deposito_ACHAsync(request);
        }
        
        public System.Threading.Tasks.Task<AchEntura.Deposito_ACHResponse> Deposito_ACHAsync(AchEntura.DatosAbono envio)
        {
            AchEntura.Deposito_ACHRequest inValue = new AchEntura.Deposito_ACHRequest();
            inValue.Body = new AchEntura.Deposito_ACHRequestBody();
            inValue.Body.envio = envio;
            return ((AchEntura.ACH_ServiceSoap)(this)).Deposito_ACHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AchEntura.Actualizacion_Envio_ACHResponse AchEntura.ACH_ServiceSoap.Actualizacion_Envio_ACH(AchEntura.Actualizacion_Envio_ACHRequest request)
        {
            return base.Channel.Actualizacion_Envio_ACH(request);
        }
        
        public AchEntura.RespuestaActualizacionEnvio Actualizacion_Envio_ACH(AchEntura.DatosActualizacionEnvio datos)
        {
            AchEntura.Actualizacion_Envio_ACHRequest inValue = new AchEntura.Actualizacion_Envio_ACHRequest();
            inValue.Body = new AchEntura.Actualizacion_Envio_ACHRequestBody();
            inValue.Body.datos = datos;
            AchEntura.Actualizacion_Envio_ACHResponse retVal = ((AchEntura.ACH_ServiceSoap)(this)).Actualizacion_Envio_ACH(inValue);
            return retVal.Body.Actualizacion_Envio_ACHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AchEntura.Actualizacion_Envio_ACHResponse> AchEntura.ACH_ServiceSoap.Actualizacion_Envio_ACHAsync(AchEntura.Actualizacion_Envio_ACHRequest request)
        {
            return base.Channel.Actualizacion_Envio_ACHAsync(request);
        }
        
        public System.Threading.Tasks.Task<AchEntura.Actualizacion_Envio_ACHResponse> Actualizacion_Envio_ACHAsync(AchEntura.DatosActualizacionEnvio datos)
        {
            AchEntura.Actualizacion_Envio_ACHRequest inValue = new AchEntura.Actualizacion_Envio_ACHRequest();
            inValue.Body = new AchEntura.Actualizacion_Envio_ACHRequestBody();
            inValue.Body.datos = datos;
            return ((AchEntura.ACH_ServiceSoap)(this)).Actualizacion_Envio_ACHAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ACH_ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ACH_ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ACH_ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://test.entura.com.mx:4110/ACH_Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ACH_ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://test.entura.com.mx:4110/ACH_Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ACH_ServiceSoap,
            
            ACH_ServiceSoap12,
        }
    }
}
